# Configuration for GitHub Actions Labeler
# Only uses existing GitHub labels to avoid permission issues

# Documentation changes - use default 'documentation' label
documentation:
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*', 'CLAUDE.md', 'MCP_SETUP.md']

# Enhancement/feature PRs - use default 'enhancement' label
enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/']
  - changed-files:
    - any-glob-to-any-file: ['src/**/*.py', 'main.py', 'weather.py']

# Bug fixes - use default 'bug' label
bug:
  - head-branch: ['^fix/', '^bugfix/', '^hotfix/']

# Dependencies - use default 'dependencies' label
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['pyproject.toml', 'uv.lock', 'requirements*.txt']
